server.port=8082
server.address=127.0.0.1

# Configurações NFe
nfe.environment=homologacao
nfe.uf=SP
nfe.cnpj=10787210000125
nfe.keystorePath=
nfe.keystorePassword=

# Configurações específicas para produção (descomente quando for usar produção)
# nfe.environment=producao
# nfe.keystorePath=/path/to/certificado.pfx
# nfe.keystorePassword=sua_senha